/* Problems worth building a startup around. One row per problem:
   [title, field, difficulty (1 Easy, 2 Medium, 3 Hard, 4 Moonshot), who pays, why it is still unsolved, a first step, source?]
   A source is only attached where the quoted line was read on the linked page. */
(function () {
  "use strict";

  var S = {
    farmers: { quote: "Middlemen form cartels and gobble up much of the profits.", by: "BBC News", url: "https://www.bbc.com/news/world-asia-india-55157574" },
    foodloss: { quote: "Around 14 per cent of food produced globally is lost between harvest and retail.", by: "UN News, citing the FAO", url: "https://news.un.org/en/story/2020/09/1074122" },
    hunger: { quote: "More than 730 million people living in hunger around the world.", by: "The Guardian", url: "https://www.theguardian.com/environment/2024/mar/27/fifth-of-food-wasted-globally-at-cost-of-1tn-a-year-says-un-report" },
    cancer: { quote: "An estimated 20.6m cases, and 10m deaths, from cancer every year.", by: "The Guardian, on a WHO report", url: "https://www.theguardian.com/global-development/2026/jul/08/health-who-global-persistent-inequities-progress-cancer-prevention-diagnosis-treatment-care" },
    steroids: { quote: "An estimated 500,000 people in the UK using anabolic steroids.", by: "BBC News", url: "https://www.bbc.com/news/articles/cdd9vg632pzo" },
    voice: { quote: "Yelp debuts AI voice agents for restaurants and service providers.", by: "TechCrunch", url: "https://techcrunch.com/2025/04/29/yelp-is-adding-ai-powered-voice-agents-for-restaurants-and-services/" },
    carehomes: { quote: "Staff shortages force closure of rural care homes.", by: "BBC News", url: "https://www.bbc.com/news/articles/cwyn642xl6jo" },
    teleport: { quote: "Teleportation: Photon particles today, humans tomorrow?", by: "BBC News", url: "https://www.bbc.com/news/science-environment-40594387" }
  };

  var AG = "Agriculture", BIO = "Biology & Health", SCI = "Science & Deep Tech", LOC = "Local Business",
    ELD = "Elder Care", CLI = "Climate & Energy", EDU = "Education", FIN = "Finance", LOG = "Logistics",
    MFG = "Manufacturing", SW = "Software & AI", GOV = "Government & Civic";

  var rows = [
    // Agriculture
    ["Small farmers still sell through middlemen", AG, 2, "Farmers, through a small cut of a better price, and buyers who want a direct supply.", "Middlemen also give credit, transport and a guaranteed buyer. A marketplace that only lists prices replaces none of that.", "Pick one crop in one district. Call ten farmers and five buyers and broker a single direct sale by hand.", S.farmers],
    ["Food is lost between the farm and the store", AG, 3, "Farmer groups, food processors and retailers who lose stock they already paid for.", "It needs storage, transport and handling to improve together, in places where every one of them is thin.", "Follow one crop from field to market for a week and write down where it spoils and what that costs.", S.foodloss],
    ["Surplus food does not reach hungry people", AG, 3, "Food banks, city governments, and retailers who pay to dump unsold food.", "Surplus shows up at random times and places, and moving it safely often costs more than the food is worth.", "Ask three local shops what they throw away each night, and one charity what it can collect.", S.hunger],
    ["Cold storage a small farmer can afford", AG, 3, "Farmers and cooperatives growing fruit, vegetables, milk or fish.", "Cold rooms need steady power and capital, and one small farm cannot fill one alone.", "Find a village with a shared need and price one solar cold room rented by the crate per day."],
    ["Crop disease found too late", AG, 2, "Farmers, seed and input companies, crop insurers.", "Photo diagnosis works in a lab. It struggles in bad light, on local varieties and in local languages.", "Collect 200 labelled photos of one disease on one crop from farmers near you and test an existing model on them."],
    ["Soil tests take weeks to come back", AG, 2, "Farmers who overspend on fertiliser, and the companies who sell it.", "Accurate tests need a lab. Cheap field sensors drift and farmers stop trusting them.", "Offer a paid soil test with a three day turnaround to twenty farms, using a lab that already exists."],
    ["Farmers get weather and price news too late", AG, 1, "Farmer groups, input dealers and local banks who want to stay in touch with farmers.", "Most alerts are in English or in text, and many farmers prefer a voice message in their own language.", "Start a WhatsApp voice note every morning for one village with the local price and the weather."],
    ["Tractors sit idle while neighbours need one", AG, 2, "Farmers who cannot afford a machine, and owners who want it earning.", "Everyone needs the machine in the same two weeks, and breakdowns start arguments.", "Run a booking sheet for the machines in one village through a single harvest."],
    ["Crop insurance claims take months", AG, 3, "Insurers and governments that subsidise crop cover.", "Checking a loss means sending someone to the field. Satellite checks are not yet trusted in disputes.", "Study how one insurer verifies claims and where the wait actually comes from."],
    ["Small dairy farms keep no records", AG, 1, "Dairy farmers and the cooperatives that buy their milk.", "Paper notebooks get lost, and most farm software is built for large herds.", "Build a phone log for milk yield, feed and vet visits and give it to five farmers."],
    ["Cereal crops that make their own fertiliser", AG, 4, "Every grain farmer, and governments that subsidise fertiliser.", "Beans can pull nitrogen from the air with the help of bacteria. Getting wheat, rice or maize to do the same is unsolved biology.", "Read the current research on nitrogen fixation in cereals and find a lab you could join or support."],

    // Biology & Health
    ["Cancers that still have no cure", BIO, 4, "Patients, health systems and insurers.", "Cancer is hundreds of different diseases, and tumours change to resist the drugs that work at first.", "Pick one rare cancer and map every open trial and research group working on it.", S.cancer],
    ["Muscle drugs with no side effects", BIO, 3, "Hospitals treating muscle wasting, older patients, and athletes.", "The pathways that build muscle also act on the heart, the liver and hormones.", "Read the published trials on the newer muscle drugs and list why each one stalled.", S.steroids],
    ["Cancer caught too late", BIO, 3, "Health systems, insurers and employers.", "A blood test has to find a faint signal without scaring healthy people with false alarms.", "Talk to an oncologist about which cancer in your region is found latest, and why."],
    ["Infections that antibiotics no longer cure", BIO, 3, "Hospitals and governments.", "A new antibiotic is used as little as possible to keep it working, so it earns too little to pay for its development.", "Study the payment models some governments are testing to reward new antibiotics."],
    ["Patients do not show up for appointments", BIO, 1, "Clinics, dentists and physiotherapists who lose money on every empty slot.", "Reminders exist, but most small clinics still phone people by hand and never refill the slot.", "Offer one clinic WhatsApp reminders and a waiting list for a month, and count the slots saved."],
    ["Medical records do not follow the patient", BIO, 3, "Hospitals, insurers and governments.", "Every hospital system stores data in its own way, and nobody is paid to share it.", "Build something small that lets a patient photograph and carry their own records, and test it with ten families."],
    ["Months of waiting to see a therapist", BIO, 2, "Employers, insurers, universities and patients.", "There are too few trained therapists, and software alone is not trusted for serious cases.", "Find one clinic with a long waiting list and ask what would help people during the wait."],
    ["No treatment stops Alzheimer's", BIO, 4, "Families, health systems and insurers.", "The cause is still argued over, and damage starts years before anyone notices symptoms.", "Read where current trials are aimed and which early detection methods look promising."],
    ["Rural clinics cannot run basic tests", BIO, 3, "Governments, charities and rural health providers.", "Test machines need power, supplies, trained staff and maintenance, and all of those are scarce far from a city.", "Visit one rural clinic and list the tests it sends away and how long the results take."],
    ["People stop taking their medicine", BIO, 2, "Insurers, pharmacies and drug makers.", "Reminder apps get ignored. The real reasons are cost, side effects and confusion.", "Call twenty patients for one pharmacy and ask why they missed a refill."],
    ["Lab reports nobody can read", BIO, 1, "Diagnostic labs that want patients to come back, and patients themselves.", "Reports are written for doctors, and labs worry about being blamed for advice.", "Build a plain language summary for one common report and show it to a lab owner."],

    // Science & Deep Tech
    ["Teleportation", SCI, 4, "Anyone who moves people or goods. Long before that, the people who need secure communication.", "So far only the state of single particles has been sent. Nothing with mass has gone anywhere.", "Learn what quantum teleportation actually moves, then look at where quantum networking startups are hiring.", S.teleport],
    ["Fusion power on the grid", SCI, 4, "Utilities and governments.", "A reactor has to give out more energy than the whole plant uses, and keep doing it for years.", "Fusion companies need suppliers and software. Find one small part of that chain you could build."],
    ["Superconductors at room temperature", SCI, 4, "Power grids, hospitals, chip makers and transport.", "Every known superconductor needs extreme cold or extreme pressure.", "Follow the materials groups using machine learning to search for candidates, and learn their tools."],
    ["Quantum computers that do useful work", SCI, 4, "Drug companies, chemical makers and banks.", "Qubits are noisy, and correcting their errors takes far more of them than anyone can build today.", "Take a free quantum programming course and run a small circuit on a real cloud machine."],
    ["Batteries that hold far more energy", SCI, 3, "Car makers, airlines and grid operators.", "A new chemistry that works in a lab often fails on safety, lifespan or cost when it is made at scale.", "Pick one narrow use, such as drones, and learn what its battery buyers complain about."],
    ["Independent researchers cannot get lab time", SCI, 2, "Small biotech teams, students and hobby scientists.", "Equipment is expensive, and university labs are closed to outsiders.", "List the shared labs near you and ask what stops people from using them."],
    ["Published results cannot be reproduced", SCI, 2, "Journals, funders and drug companies who build on published work.", "Methods are described loosely, and nobody is rewarded for repeating someone else's experiment.", "Try to reproduce one paper in your own field and write down every gap you hit."],
    ["Nobody can keep up with the papers", SCI, 1, "Research teams, R&D departments and investors.", "Search finds papers. It does not tell you which ones matter for your exact question.", "Send a weekly digest of new papers in one narrow niche to twenty people who work in it."],
    ["Space junk in orbit", SCI, 3, "Satellite operators, insurers and space agencies.", "Catching debris is hard and costly, and nobody is clearly responsible for old junk.", "Read how satellite operators handle collision warnings today and where their tools fall short."],
    ["Turning seawater into cheap fresh water", SCI, 3, "Dry cities, farms and industry.", "Desalination takes a lot of energy and leaves brine that has to go somewhere.", "Look at small solar desalination units and who buys them today."],

    // Local Business
    ["Shops miss calls while serving customers", LOC, 1, "Restaurants, salons, clinics and repair shops.", "Owners are too busy to set one up, and off the shelf tools do not know their menu, prices or hours.", "Set up a voice agent for one local shop for free, then charge the next five.", S.voice],
    ["Shops with an Instagram page and no website", LOC, 1, "Any local business that people look up before they visit.", "Owners do not know where to start, and agencies charge more than a small shop will pay.", "Build a one page site for a shop you already buy from, and ask them for an intro to the shop next door."],
    ["Reviews nobody answers", LOC, 1, "Restaurants, hotels, clinics and gyms.", "Owners see reviews late, and a bad one can sit unanswered for months.", "Draft replies to one shop's last thirty reviews and show the owner."],
    ["Bookings taken over phone calls and chat", LOC, 1, "Salons, clinics, tutors and repair services.", "Customers want to message, not install an app, and owners double book by mistake.", "Set up WhatsApp booking with a shared calendar for one salon."],
    ["Shops do not know what is in stock", LOC, 2, "Small retailers, pharmacies and hardware stores.", "Inventory software expects barcodes and discipline. Small shops have neither.", "Spend a day in one shop and count how often they say no to a customer for an item they actually had."],
    ["Freelancers and small contractors chasing payments", LOC, 1, "Designers, builders, consultants and small agencies.", "Sending the invoice is easy. Following up is awkward, so it does not happen.", "Offer to run payment reminders for three freelancers for a month."],
    ["Restaurant shifts planned on paper", LOC, 2, "Restaurants, cafes and shops with part time staff.", "Staff swap shifts in group chats, and the owner finds out when someone does not turn up.", "Take one restaurant's group chat schedule and turn it into a simple shared rota."],
    ["Delivery apps take a big cut", LOC, 2, "Restaurants and grocers with regular local customers.", "The apps own the customer, and one shop cannot run its own delivery fleet.", "Help one restaurant take direct orders from its regulars and measure what it keeps."],
    ["Menus and prices out of date everywhere", LOC, 1, "Restaurants listed on several delivery and map apps.", "Every platform has its own dashboard, so a price change means doing the same edit five times.", "Offer a flat monthly fee to keep one restaurant's listings in sync."],
    ["Bookkeeping in cash businesses", LOC, 2, "Shop owners and the accountants who clean up after them.", "Receipts live in a drawer, and the books are rebuilt once a year at tax time.", "Photograph and sort one shop's receipts for a month and hand the result to their accountant."],

    // Elder Care
    ["Care homes cannot find or keep staff", ELD, 2, "Care home operators and the families who pay the fees.", "The work is hard and low paid, and paperwork eats the hours that are left.", "Shadow a shift in one care home and time how long goes on notes and handovers.", S.carehomes],
    ["Falls that nobody notices", ELD, 2, "Families, care homes and insurers.", "People refuse to wear alarm pendants, and cameras feel like being watched.", "Interview ten families about what they tried and why they stopped using it."],
    ["Older people living alone are lonely", ELD, 2, "Families living far away, housing providers and health services.", "Technology cannot replace company, and volunteer visiting schemes do not scale.", "Run a weekly phone call circle for ten older people and see who keeps coming."],
    ["Missed medicines, and family find out late", ELD, 1, "Adult children looking after a parent from a distance.", "Pill boxes do not tell anyone anything, and smart ones are fiddly to set up.", "Set up a daily check in message that alerts a family member if there is no reply."],
    ["Finding a carer you can trust", ELD, 2, "Families who need help at home.", "Background checks, training and reliability are hard to verify, and good carers are booked.", "Vet and list twenty carers in one neighbourhood and match them by hand."],
    ["Care home paperwork", ELD, 1, "Care home managers.", "Notes are handwritten because staff are on their feet, and inspectors still need records.", "Build voice notes that turn into shift records and trial them on one ward."],
    ["Dementia care at home", ELD, 3, "Families, insurers and health systems.", "Needs change every month and carers burn out. A care home costs more than most families can pay.", "Talk to five family carers about their hardest hour of the day."],
    ["Phones and apps older people cannot use", ELD, 1, "Their families, and banks, clinics and shops that want them as customers.", "Apps change all the time, and scam fears make people give up.", "Offer a paid home visit to set up a parent's phone, video calls and banking safely."],
    ["Getting to medical appointments", ELD, 2, "Hospitals with no-shows, insurers and families.", "Taxis are expensive, and public transport is hard with a walker or a wheelchair.", "Coordinate rides for one clinic's older patients for a month."],
    ["Scams aimed at older people", ELD, 2, "Banks, phone companies and families.", "Scammers change their script faster than warnings can spread.", "Collect the scam calls and messages older people near you actually get and write a simple guide."],

    // Climate & Energy
    ["Storing clean power for days", CLI, 3, "Utilities and grid operators.", "Batteries cover a few hours cheaply. Covering days or a whole season is still too expensive.", "Learn how your local grid pays for storage and who is allowed to bid."],
    ["Pulling carbon out of the air", CLI, 4, "Companies with climate pledges, and governments.", "It takes a lot of energy per tonne, and proving the carbon stays stored is hard.", "Study how removal is measured and verified. That part needs software today."],
    ["Energy bills nobody understands", CLI, 1, "Households and small businesses.", "Tariffs are confusing, and switching feels risky.", "Read ten friends' bills and tell each one what they could save."],
    ["Rooftop solar wrapped in paperwork", CLI, 2, "Homeowners and solar installers.", "Permits, subsidies and grid approval can take longer than the installation.", "Handle the paperwork for one installer's next five jobs."],
    ["Cooling hot cities", CLI, 3, "City governments, landlords and employers.", "Air conditioning heats the street outside and loads the grid at its worst hour.", "Measure the temperature in ten homes on your street and find the cheapest thing that helps."],
    ["Plastic that says recyclable and is not recycled", CLI, 3, "Consumer brands, recyclers and city governments.", "Sorting mixed plastic costs more than new plastic.", "Visit a recycling plant and ask which materials they turn away, and why."],
    ["Charging an electric car in an apartment block", CLI, 2, "Building owners and residents.", "Shared wiring, shared bills, and nobody wants to pay for the upgrade.", "Work out the wiring and billing for one building and write up the plan."],
    ["Cement and steel without the emissions", CLI, 3, "Construction firms, car makers and governments.", "The chemistry itself releases carbon, and plants are built to run for decades.", "Read up on the low carbon cement startups and where their pilot plants stand."],
    ["Small companies asked for a carbon report", CLI, 1, "Suppliers whose large customers now demand one.", "The tools are made for big companies with a sustainability team.", "Do one small supplier's first report by hand and note every step you could automate."],
    ["Cities lose water through leaking pipes", CLI, 2, "Water utilities and city governments.", "The pipes are old and buried, and finding a leak means digging.", "Ask your water utility how it finds leaks today and what data it has."],

    // Education
    ["One teacher for forty students", EDU, 2, "Schools, parents and governments.", "Personal tutoring works, but there are not enough tutors and most families cannot afford one.", "Tutor five students with an AI assistant and write down where it helps and where it fails."],
    ["Teachers spend evenings marking", EDU, 1, "Teachers, schools and tutoring centres.", "Feedback has to be specific to each student, and teachers do not trust automatic grades.", "Help one teacher draft feedback on a single assignment and ask what they had to change."],
    ["Coding and AI lessons only in English", EDU, 1, "Students, colleges and employers in non English speaking regions.", "Good material is translated late, if at all.", "Teach one short course in your own language and post it for free."],
    ["Graduates who cannot get a first job", EDU, 2, "Students, colleges and companies that hire juniors.", "Degrees do not show what someone can do, and employers want experience.", "Run a four week project group where students ship something real for a local business."],
    ["Exam coaching families cannot afford", EDU, 2, "Parents and students.", "Good coaching depends on a few teachers in big cities.", "Record clear explanations for the hardest chapter of one exam and see who shares them."],
    ["Parents find out late that their child is behind", EDU, 1, "Schools and parents.", "Report cards come twice a year, and teachers have no time for updates.", "Send a short weekly message home for one class and ask parents if it helps."],
    ["Adults whose jobs are changing", EDU, 3, "Employers, governments and workers.", "People with jobs and families cannot stop to study, and courses do not lead to a hire.", "Talk to ten people who switched careers and map what actually got them hired."],
    ["Learning difficulties spotted years late", EDU, 3, "Schools, parents and health services.", "Assessments are costly and specialists are few.", "Learn how screening for dyslexia works and where the waiting lists are."],
    ["Schools with no science lab", EDU, 2, "Schools, charities and governments.", "Equipment costs money and needs a trained teacher.", "Build five experiments from things found at home and test them in one classroom."],
    ["Scholarships students never hear about", EDU, 1, "Students and parents, and colleges that want applicants.", "Information is scattered and deadlines are easy to miss.", "Put together a list of scholarships for one city and one subject and keep it up to date."],

    // Finance
    ["Small businesses wait months to be paid", FIN, 2, "Suppliers, and lenders who can advance the money.", "Big buyers set the terms, and lenders cannot easily tell which invoices are real.", "Ask ten small suppliers how long they wait and what it costs them."],
    ["Sending money abroad costs too much", FIN, 3, "Migrant workers and their families, and small importers.", "Every country has its own rules and banks, and the last step into cash is expensive.", "Compare the real cost on one route, such as the Gulf to India, across every provider."],
    ["Freelancers dread tax season", FIN, 2, "Freelancers and gig workers.", "Income arrives from many places, and the rules change with each kind of work.", "Do the taxes for five freelancers with an accountant and note the questions that repeat."],
    ["No credit history, no loan", FIN, 3, "Lenders looking for new customers, and borrowers.", "Without a record, lenders cannot price the risk, and other data raises privacy and fairness questions.", "Study how one small lender makes decisions for first time borrowers."],
    ["Subscriptions people forgot they have", FIN, 1, "Consumers and small businesses.", "Charges are small and spread across cards, and cancelling is made awkward on purpose.", "Go through three friends' statements and cancel what they do not use."],
    ["Expense reports", FIN, 1, "Small companies and their accountants.", "Receipts get lost, and nobody files until the deadline.", "Collect one team's receipts over WhatsApp for a month and deliver a clean sheet."],
    ["Payment scams", FIN, 3, "Banks, payment apps and their customers.", "The victim approves the payment, so the usual fraud checks do not fire.", "Document the top five scams in your country and how each payment actually moves."],
    ["Gig workers with nothing saved for retirement", FIN, 3, "Workers, platforms and governments.", "Income is irregular, and nobody takes a contribution out of each payment for them.", "Ask twenty delivery riders how they save today."],
    ["Insurance claims that drag on for weeks", FIN, 2, "Insurers and their customers.", "Documents arrive in pieces, and every claim is checked by hand.", "Help five people file a claim and time every step."],
    ["First salary, no idea what to do with it", FIN, 1, "Young earners, employers and banks.", "School does not teach it, and most advice online is selling something.", "Write a plain one page guide for a first salary in your country and share it."],

    // Logistics
    ["Addresses that are not on any map", LOG, 2, "Delivery companies and online sellers.", "Many homes have no formal address, so drivers phone the customer for directions.", "Ride along with a delivery driver for a day and count the calls."],
    ["Trucks driving home empty", LOG, 2, "Truck owners and the companies that ship goods.", "Loads are arranged through brokers and phone calls, and trust between strangers is low.", "Match return loads by hand for five truck owners on a single route."],
    ["Export paperwork for small sellers", LOG, 2, "Small exporters and freight forwarders.", "Each country and product has its own forms, and one mistake holds the goods at the port.", "Walk one small exporter's shipment through every document and write the checklist."],
    ["Returning an online order", LOG, 2, "Online stores and marketplaces.", "The product has to be collected, checked and resold, and that often costs more than it is worth.", "Ask a small online store what happens to its returns."],
    ["Tracking parcels across many couriers", LOG, 1, "Small online sellers.", "Each courier has its own tracking page, so customers message the seller to ask.", "Give one seller a single tracking page and automatic updates for their customers."],
    ["Warehouse picking mistakes", LOG, 2, "Warehouses and online stores.", "Scanners and robots are priced for big operators.", "Count the picking errors in one small warehouse for a week and find the cause."],
    ["Keeping vaccines and food cold on the road", LOG, 3, "Drug companies, governments and food distributors.", "Power cuts, and nobody can see when the cold chain broke.", "Look at how one distributor monitors temperature and where the blind spots are."],
    ["Port delays nobody can predict", LOG, 3, "Importers, exporters and shipping lines.", "The data sits with many parties, and weather, strikes and paperwork all interact.", "Track one trade lane with public data for a month and see how well you can predict delays."],
    ["Deliveries stuck in city traffic", LOG, 3, "Retailers, restaurants and couriers.", "Roads are full, and drones or robots still face rules, noise complaints and weather.", "Map the delivery times in one neighbourhood by hour of day."],
    ["Moving house", LOG, 1, "Families and students who are moving.", "Quotes vary a lot, and you cannot check a mover's quality in advance.", "Collect and compare quotes for five people who are moving this month."],

    // Manufacturing
    ["Factories run on paper and spreadsheets", MFG, 2, "Small and mid sized factories.", "Factory software is costly and built for big plants with their own IT staff.", "Digitise one production line's daily sheet and show the owner a weekly chart."],
    ["Machines that break without warning", MFG, 2, "Factories where one stopped machine stops the whole line.", "Old machines have no sensors, and breakdowns are too rare to train a model on quickly.", "Fit a cheap vibration sensor to one machine and log it for a month."],
    ["Quality checks done by eye", MFG, 2, "Makers of parts, textiles and packaged goods.", "Every product and defect is different, so each camera system is a custom job.", "Photograph good and bad parts on one line and try a simple classifier."],
    ["Finding a factory for a small batch", MFG, 2, "Hardware startups and small brands.", "Factories want large orders, and a small buyer cannot judge quality from far away.", "List the factories in one city that accept small orders for one type of product."],
    ["Quotes for custom parts take days", MFG, 1, "Machine shops, and the engineers who buy from them.", "Someone has to read the drawing and estimate time and material.", "Help one machine shop answer every quote request within a day."],
    ["Skilled workers retire and the know-how goes with them", MFG, 2, "Factories with an ageing workforce.", "The knowledge lives in people's hands and habits, not in a manual.", "Record one expert doing a setup, turn it into a step by step guide, and test it on a new hire."],
    ["Making chips without a giant factory", MFG, 4, "Chip designers, research labs and governments.", "Modern chips need the most precise and expensive machines ever built.", "Read about small scale and open source chip fabrication projects."],
    ["Factory robots that are hard to retrain", MFG, 3, "Factories that make many products in small runs.", "Every new product means days of programming by a specialist.", "Learn how one small factory uses its robot and how long a changeover takes."],
    ["Supplier delays found out too late", MFG, 1, "Purchasing teams at small manufacturers.", "Updates arrive by email and phone, and nobody chases until a part is already missing.", "Chase one buyer's open orders every week and report what is slipping."],
    ["Scrap and waste material", MFG, 2, "Factories that cut metal, fabric, wood or plastic.", "Offcuts vary in shape and size, and tracking them takes effort.", "Weigh one factory's scrap for a week and find the largest source."],

    // Software & AI
    ["AI agents nobody trusts to run alone", SW, 3, "Every company trying to put agents to work.", "They fail in ways that are hard to predict or test, and one bad action can be costly.", "Build a small agent for a real task and log every failure for a month."],
    ["Company knowledge nobody can find", SW, 2, "Any team of more than twenty people.", "Answers are spread across chat, documents and people's heads, and they go stale.", "Make a searchable set of answers for one team from the questions they asked last quarter."],
    ["Support inboxes at small software companies", SW, 1, "Small software companies and online stores.", "Founders answer the same questions by hand, and generic bots give wrong answers.", "Answer one product's support mail with AI drafts that a human approves."],
    ["Old code nobody dares to touch", SW, 3, "Banks, insurers and governments.", "The people who wrote it have left, there are no tests, and the business depends on it.", "Pick one open source legacy project and try to modernise a single module with AI help."],
    ["Meetings with no follow up", SW, 1, "Teams and consultants.", "Notes get taken. Tasks do not reach the people who own them.", "Turn one team's meeting recordings into assigned tasks for two weeks."],
    ["Cleaning data before any analysis", SW, 2, "Analysts and operations teams.", "Every company's data is messy in its own way.", "Clean one real spreadsheet for a small business and save the steps as a script."],
    ["Security for teams with no security person", SW, 2, "Startups and small agencies.", "Audits are expensive, and scanners produce long lists nobody reads.", "Run a basic security check for three small companies and fix the top five issues with them."],
    ["AI that states wrong things with confidence", SW, 3, "Law firms, hospitals, banks and newsrooms.", "Models write fluent text without knowing when they are wrong.", "Pick one narrow domain and build a checker that verifies every claim against a trusted source."],
    ["Websites that shut out disabled users", SW, 1, "Businesses with a legal duty to be accessible, and their agencies.", "Developers do not test with screen readers, and automated checks miss a lot.", "Audit three local business websites and send each a list of fixes."],
    ["Running AI models on ordinary hardware", SW, 3, "Companies that cannot send their data to the cloud.", "The best models need expensive chips and a lot of memory.", "Get a small open model working on a laptop for one real task and measure the quality."],

    // Government & Civic
    ["Government forms people cannot fill in alone", GOV, 1, "Citizens, and the agents who charge to do it for them.", "The forms are long, the wording is legal, and a mistake means starting again.", "Write a plain step by step guide for one common form and help ten people use it."],
    ["Benefits people qualify for and never claim", GOV, 2, "Governments, charities and citizens.", "The rules are spread across departments, and people do not know what exists.", "List every scheme for one group in your state, such as students or farmers."],
    ["Pothole reports that go nowhere", GOV, 1, "City governments and residents' groups.", "Complaints arrive through many channels, and nobody reports back.", "Map and photograph the problems on one street and send a single clear report."],
    ["Courts with years of backlog", GOV, 3, "Governments, law firms and people waiting on a case.", "There are too few judges, hearings get postponed, and records are on paper.", "Sit in a local court for a day and note why hearings are postponed."],
    ["Land records that cause disputes", GOV, 3, "Governments, banks and property buyers.", "Records are old, on paper, and sometimes contradict each other.", "Trace the paperwork for one property purchase from start to finish."],
    ["Public tenders small firms never see", GOV, 1, "Small businesses that could supply government.", "Notices are spread over many portals and written in dense language.", "Send a weekly digest of tenders in one category to twenty small firms."],
    ["Ambulances that arrive late", GOV, 3, "Governments and hospitals.", "Dispatch, traffic and hospital capacity are run by different bodies.", "Read up on how emergency dispatch works in your city."],
    ["Bus times nobody can rely on", GOV, 2, "Transport agencies and commuters.", "Buses lack trackers, or the data is never published.", "Track one bus route by hand for a week and publish the real timetable."],
    ["False rumours during elections and disasters", GOV, 3, "Platforms, newsrooms and governments.", "A rumour spreads faster than a correction, and people trust their own group chats.", "Start a verified updates channel for your neighbourhood during the next local emergency."],
    ["An identity that works in every country", GOV, 3, "Governments, banks and travellers.", "Every country has its own system, and privacy and trust are hard to agree on.", "Learn how one digital identity system works and where it breaks for migrants."]
  ];

  window.PROBLEMS = rows.map(function (r, i) {
    return { id: i + 1, title: r[0], field: r[1], level: r[2], pays: r[3], why: r[4], step: r[5], source: r[6] || null };
  });
})();
